# Generated by Django 4.1.12 on 2024-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('site', models.URLField(max_length=256)),
                ('name_site', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
    ]
